BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBB
    XXXX XXXXXXXX XXXX
BBBBBBBB
BBBBB BBBBBBB
    XXXXXXXX XXXXXXXX XXXXXXXXX
    XXXXXX XXXXXXXXXXXXX
        XXXXXXX
        XXXX
            XXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXX
        XXXXX
        XXXXXXXX
        XXXXXXX
        BBB BBBB BB BBBB
            BBBB BBBBBBBBBBBBBBBBBBBB
                XXXX
                    XXXX
                        XX XXXXXXXX
                            XXXX XXXXXBB BBBBBBBBBBBBB
BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
                        XXXX
                    XXXXX
                    XXXXXXXXX
                    
                    XXXX
                        XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXX
                            
                            
                            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            BBBBBBBBBB
                        XXXXXXX
                    XXXXX

                    XXXXXX XXXXXXXX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
XXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXX
                XXXXX
            BBBBBBB
        BBBBBB

        BB BBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXX
            XXXXX
            XXXX
                XXXX
                    XX XXXXXX
                    XX XXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXX XXXXX
                    X XFFFFFFFFFFFFFFF
                XXXXX
            XXXXX
        BBBBB
        XXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXX
                XFFFFFFFFFFFFFFF
            XXXXX
        XXXXX

        XXXXXXXX
    XXXXXXXX

    XXXXXXXX X XXXXXXXXXXX
XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXX

XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
BBBBBBBBBB
XXXXXXX
    XX XXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX
XXXXXXXXXXXXXXX XXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
            XXXXXXXX
        XXXXXXXX
BBBBBBBB