BBBBBBB BBBBBBBBBBB
BBBBB BBBBB
    XXXXXXXX
BBBBBBBB
BBBBB BBBBBBB
    XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXX XXXXXXXXXX
        XXXX
            BBB BBBB BB BBBB
                XXXX
                    X 
                    XXXXXXXFFFFFFFFFFFFFFFXXXXXXX
                XXXXX
            BBBBBB
            BB BBBBBBBBBBB
                XXXX
                    XX XX XXXX
                    XXXXXXX XFFFFFFFFFFFFFFFXXXXXXX
                XXXXX
            BBBBB
        XXXXX

        XXXXXXXXX XFFFFFFFFFFFFFFFXXXX
    XXXXXX
    XXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
        BBBBBBBBBB
    XXXXXXX
BBBBBBBB