# Generated by Django 3.1.7 on 2021-07-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='shablon',
            field=models.CharField(choices=[('school/product/list.html', 'Base'), ('school/product/school_list.html', 'School'), ('school/product/staff_list.html', 'Staff'), ('school/product/list2.html', 'Quotes'), ('school/product/list3.html', 'Not name')], default=1, max_length=500),
            preserve_default=False,
        ),
    ]
