# Generated by Django 3.1.7 on 2021-08-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0009_content_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('name',), 'verbose_name': 'Главная', 'verbose_name_plural': 'Главная'},
        ),
        migrations.AddField(
            model_name='slide',
            name='url',
            field=models.CharField(blank=True, default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
