# Generated by Django 3.1.7 on 2021-08-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0011_auto_20210802_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_prime_block',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content_second_block',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='image_prime_block',
            field=models.ImageField(blank=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='content',
            name='image_second_block',
            field=models.ImageField(blank=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='content',
            name='name_prime_block',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='name_second_block',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
