# Generated by Django 3.1.7 on 2021-08-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0012_auto_20210803_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='image_prime_block',
        ),
        migrations.RemoveField(
            model_name='content',
            name='image_second_block',
        ),
        migrations.AddField(
            model_name='content',
            name='url_prime_block',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='content',
            name='url_second_block',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='name_prime_block',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='name_second_block',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
