# Generated by Django 3.1.7 on 2021-08-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0016_formschool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormSchool',
        ),
    ]
