# Generated by Django 3.1.7 on 2021-08-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0017_delete_formschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='shablon',
            field=models.CharField(choices=[('singlepage/singlepage.html', 'All'), ('singlepage/page-files.html', 'Files'), ('singlepage/maps.html', 'MapsYandex'), ('singlepage/kontakty.html', 'Contakt'), ('singlepage/about.html', 'About')], max_length=500),
        ),
    ]
