# Generated by Django 3.1.7 on 2021-08-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0018_auto_20210810_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
