# Generated by Django 3.1.7 on 2021-07-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_category_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shablon',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
