# Generated by Django 3.1.7 on 2021-07-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_category_shablon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shablon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('urltemplate', models.CharField(max_length=550)),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'ordering': ('name',),
            },
        ),
    ]
