# Generated by Django 3.1.7 on 2021-07-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_shablon_attr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='shablon',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='Freshman', max_length=500),
        ),
    ]
