# Generated by Django 3.1.7 on 2021-07-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20210712_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='shablon',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('school/product/list.html', 'Senior'), ('GR', 'Graduate')], default='Freshman', max_length=500),
        ),
    ]
