# Generated by Django 3.1.7 on 2021-07-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20210712_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='shablon',
            field=models.CharField(choices=[('school/product/list.html', 'Base'), ('school/product/list.html', 'School'), ('school/product/list.html', 'Staff'), ('school/product/list.html', 'Quotes'), ('school/product/list.html', 'Not name')], default='Base', max_length=500),
        ),
    ]
