# Generated by Django 3.1.7 on 2021-07-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20210712_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shablon',
        ),
    ]
