# Generated by Django 3.1.7 on 2021-07-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20210712_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='shablon',
        ),
    ]
