# Generated by Django 3.1.7 on 2021-07-20 14:46

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_product_price_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
