# Generated by Django 3.1.7 on 2021-07-26 18:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_auto_20210721_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
