# Generated by Django 3.1.7 on 2021-07-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210709_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='adress',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='mail',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='phone',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='yandexmap',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
    ]
