# Generated by Django 3.1.7 on 2021-07-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_singlepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Pages',
        ),
        migrations.DeleteModel(
            name='Kontakt',
        ),
        migrations.DeleteModel(
            name='SinglePage',
        ),
    ]
