# Generated by Django 3.1.7 on 2021-08-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210802_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=200),
            preserve_default=False,
        ),
    ]
