# Generated by Django 3.1.7 on 2021-08-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210802_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, upload_to='slide/'),
        ),
    ]
