# Generated by Django 3.1.7 on 2021-07-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='cars/%Y/%m/%d')),
                ('title', models.CharField(blank=True, max_length=170, null=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('year', models.CharField(blank=True, max_length=200, verbose_name='Год')),
                ('car_model', models.CharField(blank=True, max_length=200, verbose_name='Модель машины')),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
