# Generated by Django 3.1.7 on 2021-07-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='gos',
            field=models.CharField(blank=True, max_length=200, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='cars',
            name='transmission',
            field=models.CharField(blank=True, choices=[('Автоматическая', 'Автоматическая'), ('Механическая', 'Механическая')], max_length=500),
        ),
    ]
