# Generated by Django 3.1.7 on 2021-07-11 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_category_updated'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер Телефона')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.product', verbose_name='Быстрый курс')),
            ],
        ),
    ]
