# Generated by Django 3.1.7 on 2021-07-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_fastorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fastorder',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fastorder',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
