# Generated by Django 3.1.7 on 2021-07-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210711_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FastOrder',
        ),
    ]
